# Generated by Django 6.0.2 on 2026-03-14 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('marketplace', '0002_remove_product_category_remove_product_producer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_unit', models.CharField(choices=[('EACH', 'Each'), ('PACK', 'Pack'), ('BUNCH', 'Bunch'), ('BOX', 'Box'), ('DOZEN', 'Dozen'), ('G', 'Gram (g)'), ('KG', 'Kilogram (kg)'), ('ML', 'Millilitre (ml)'), ('L', 'Litre (l)')], max_length=10)),
                ('stock_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('product_stock_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('best_before_date', models.DateField(blank=True, null=True)),
                ('organic_status', models.CharField(choices=[('ORGANIC', 'Organic'), ('NON_ORGANIC', 'Non-Organic')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounts.producerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_type', models.CharField(choices=[('SEASONAL', 'Seasonal'), ('YEAR_ROUND', 'Year Round')], max_length=20)),
                ('start_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('end_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expires_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('image_sort_order', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.allergen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'allergen'), name='unique_product_allergen')],
            },
        ),
    ]
