# Generated by Django 6.0.2 on 2026-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_product_current_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_amount', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('allergy_info', models.CharField(max_length=500)),
                ('harvest_date', models.DateTimeField()),
                ('product_image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
