# Generated by Django 6.0.2 on 2026-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_addproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='allergy_info',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='harvest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
