# Generated by Django 6.0.2 on 2026-05-06 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='availability_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfilled_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
