# Generated by Django 6.0.2 on 2026-05-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_stocknotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdeal',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
